openapi: 3.1.0
info:
  title: SYNDESIS API
  version: 1.0.0
servers:
  - url: https://syndesis.social      # ☑️ πλήρης HTTPS URL
paths:
  /health:
    get:
      operationId: health
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
