openapi: 3.0.1
info:
  title: SYNDESIS Plugin API
  description: OpenAPI definition for SYNDESIS plugin
  version: "1.0.0"
paths:
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: OK